### ISSUE TITLE
Add a central, managed way to access the WebApi for .NET clients

### ISSUE THREAD

**Issue by ThorstenSauter** [Code2Gether-Discord/Congo#53]
In order to facilitate easy access to the WebApi endpoints, the API team should provide a managed way of interaction for other .NET projects.

To that effect I propose adding a [Refit](https://reactiveui.github.io/refit/) client to the Contracts project, which will allow consumers of the API to use the existing requests and responses to interact with the WebApi.

Example of the client:
```cs
namespace Congo.Contracts {

    public interface ICongoClient
    {
        [Get("/api/products")]
        Task<ApiResponse<IEnumerable<ProductResponse>>> GetProducts();

        ...
    }
}
```

Example of client registration:
```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddRefitClient<ICongoClient>()
        .ConfigureHttpClient(c => c.BaseAddress = new Uri("https://localhost:5001"))

    ...
```

If we were to use Refit, there is still the question of whether we want to provide methods that return an `ApiResponse<T>` or the response object directly. The former gives more control to the user, so that would probably be more applicable for a general use case.

**Comment by Palisar** [comment]
Would it make more sense to add Refit to the projects themselves? I'm just a little unsure as to how we run a service from a separate project

**Comment by valincius** [comment]
> Would it make more sense to add Refit to the projects themselves? I'm just a little unsure as to how we run a service from a separate project
> 
> 

Only the spec for the refit client is shared `ICongoClient`. You'd still create the service on each app separately

**Comment by Palisar** [comment]
ah ok i got you!
