### ISSUE TITLE
Need to Add CORS to the API

### ISSUE THREAD

**Issue by Palisar** [Code2Gether-Discord/Congo#73]
Long story short, blazor can't call the API without it

**Comment by cptcrunchy** [comment]
I was able to resolve this issue but for local development. Not sure exactly on how to resolve this for "Production"

```csharp
        //Congo.WebApi -> Startup.cs
   
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Congo.WebApi v1"));
            }

            app.UseHttpsRedirection();
            // <!-- Add this CORS to allow Blazor to interact with Web API -->
            app.UseCors(policy =>
                policy.WithOrigins("http://localhost:44394", "https://localhost:44394")
                    .AllowAnyMethod()
                    .WithHeaders(HeaderNames.ContentType));

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

**Comment by Palisar** [comment]
I'm not quite sure about that one either

**Comment by U-C-S** [comment]
I am working on this issue 

Progress can be seen here: https://github.com/Code2Gether-Discord/Congo/blob/feature/73-cors-api/src/Congo.WebApi/Startup.cs

As for the moment, it's working good i.e
- can be accessible from any origin in Dev
- a environment variable ALLOWED_ORIGIN can be set in production environments to Enable CORS for the specific origin.

I need to test it more. Also need to allow CORS for multiple origins
